title: "A Game Developer's Diary"
description: "This is where I write about all my awesome game dev experiments"
about: "My experiments as a game developer "
location: "Orlando, Florida"
email: sanjay.mnambiar@gmail.com
baseurl: ""

url: "https://sanjay-nambiar.github.io"
twitter_username: mr_snambiar
linkedin_profile: "in/sanjaymnambiar"
github_username:  sanjay-nambiar
author: "Sanjay Nambiar"

# google analytics tracking code, please change the value
g_analytics: "UA-84310090-1"

# add your disqus to enable comments
disqus_shortname: game-developers-diary

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
about_btn: "About"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'tag-list'
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

# third party gems
gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-gist
  - gemoji

whitelist:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-gist
  - gemoji

# exclude files
exclude:
  - LICENSE
  - README.md
